name: Build Python Program to EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows runners for direct compatibility
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Adjust to your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        choco install zip

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile main.py --name SecureEncryptionSystem

    - name: Package Executable
      shell: bash
      run: |
        set -euxo pipefail
        mkdir -p dist
        mv dist/SecureEncryptionSystem.exe .
        zip -r SecureEncryptionSystem.zip SecureEncryptionSystem.exe
        echo "archive=SecureEncryptionSystem.zip" >> $GITHUB_OUTPUT

   # - name: Publish Executable
  #    shell: bash
 #     env:
#        archive: ${{ steps.package.outputs.archive }}
#      run: |
##        curl -T "$archive" "https://transfer.sh/$(basename $archive)"

    - name: Push changes
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Compiling changes"
        git push origin main