name: Build Python Program to EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build EXE for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Pull Latest Code From Repository
        run: git pull
      
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CipherCraft/requirements.txt
          pip install pyinstaller

      - name: Clean Previous Builds
        run: |
          Remove-Item -Recurse -Force dist/windows/*

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile CipherCraft/main.py --name CipherCraft

      - name: Package Executable
        run: |
          echo "Packaging Windows executable..."
          mkdir -Force dist/windows
          Move-Item -Force dist/CipherCraft.exe dist/windows/CipherCraft.exe
          Compress-Archive -Path dist/windows/* -DestinationPath dist/windows/CipherCraft.zip
          echo "archive=dist/windows/CipherCraft.zip" >> $GITHUB_ENV

      - name: Commit Changes to dist
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/windows/*
          git commit -m "Update Windows dist artifacts"
          git push origin HEAD

  build-linux:
    name: Build EXE for Linux
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Pull Latest Code From Repository
        run: git pull

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CipherCraft/requirements.txt
          pip install pyinstaller

      - name: Clean Previous Builds
        run: |
          rm -rf dist/linux/*

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile CipherCraft/main.py --name CipherCraft

      - name: Package Executable
        run: |
          echo "Packaging Linux executable..."
          mkdir -p dist/linux
          mv dist/CipherCraft dist/linux/CipherCraft
          zip -j dist/linux/CipherCraft.zip dist/linux/CipherCraft
          echo "archive=dist/linux/CipherCraft.zip" >> $GITHUB_ENV

      - name: Commit Changes to dist
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/linux/*
          git commit -m "Update Linux dist artifacts"
          git push origin HEAD
