name: Build Python Program to EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build EXE for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if Test-Path requirements.txt; then pip install -r requirements.txt; fi
    
    - name: Remove previous executables
      run: |
        rm -r dist/*

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile main.py --name SecureEncryptionSystem || exit 1

    - name: Package Windows Executable
      run: |
        echo "Packaging Windows executable..."
        if (!(Test-Path -Path "dist/windows")) { mkdir dist/windows }
        if (Test-Path "dist/SecureEncryptionSystem.exe") {
          mv dist/SecureEncryptionSystem.exe dist/windows/SecureEncryptionSystem.exe
        } else {
          echo "Error: Executable not found." && exit 1
        }
        cd dist/windows
        zip -r SecureEncryptionSystem.zip SecureEncryptionSystem.exe
        echo "archive=dist/windows/SecureEncryptionSystem.zip" >> $GITHUB_ENV
        echo "Windows packaging completed."

  build-linux:
    name: Build EXE for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Stable Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        [ -f requirements.txt ] && pip install -r requirements.txt || echo "No requirements.txt found."

    - name: Build Executable for Linux
      run: |
        pyinstaller --onefile main.py --name SecureEncryptionSystem || exit 1

    - name: Package Linux Executable
      run: |
        echo "Packaging Linux executable..."
        mkdir -p dist/linux
        if [ -f dist/SecureEncryptionSystem ]; then
          mv dist/SecureEncryptionSystem dist/linux/SecureEncryptionSystem
        else
          echo "Error: Executable not found." && exit 1
        fi
        cd dist/linux
        zip -r SecureEncryptionSystem.zip SecureEncryptionSystem
        echo "archive=dist/linux/SecureEncryptionSystem.zip" >> $GITHUB_ENV
        echo "Linux packaging completed."

  push-changes:
    name: Push Build Artifacts
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Push Build Changes
      if: ${{ github.ref_name == 'main' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Pushing build artifacts..."
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add dist
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Added build artifacts for Windows and Linux from GitHub Actions"
          git push origin main
          echo "Build artifacts pushed."
        fi
