name: Build Python Program to EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build EXE for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.16

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile main.py --name SecureEncryptionSystem

    - name: Package Windows Executable
      run: |
        echo "Packaging Windows executable..."
        if (!(Test-Path -Path "dist/windows")) { New-Item -ItemType Directory -Path "dist/windows" }
        mv dist/SecureEncryptionSystem.exe dist/windows/SecureEncryptionSystem.exe
        cd dist/windows
        zip -r SecureEncryptionSystem.zip SecureEncryptionSystem.exe
        echo "archive=dist/windows/SecureEncryptionSystem.zip" >> $GITHUB_OUTPUT
        echo "Windows packaging completed."


  build-linux:
    name: Build EXE for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.16

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Executable for Linux
      run: |
        pyinstaller --onefile main.py --name SecureEncryptionSystem

    - name: Package Linux Executable
      run: |
        echo "Packaging Linux executable..."
        mkdir -p dist/linux
        mv dist/SecureEncryptionSystem dist/linux/SecureEncryptionSystem
        cd dist/linux
        zip -r SecureEncryptionSystem.zip SecureEncryptionSystem
        echo "archive=dist/linux/SecureEncryptionSystem.zip" >> $GITHUB_OUTPUT
        echo "Linux packaging completed."

  push-changes:
    name: Push Build Artifacts
    needs: [build-windows, build-linux]  # Ensure this runs after both builds
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Push Build Changes
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Committing build artifacts..."
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add dist
        git commit -m "Added build artifacts for Windows and Linux from GitHub Actions"
        git push origin main
        echo "Build artifacts pushed."
