name: Build Python Program to EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build EXE for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Pull The latest Repository
        run: |
          git pull

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean Previous Builds
        run: |
          if (Test-Path -Path dist/windows) { Remove-Item -Recurse -Force dist/windows }

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile main.py --name SecureEncryptionSystem

      - name: Package Executable
        run: |
          echo "Packaging Windows executable..."
          New-Item -ItemType Directory -Force -Path dist/windows
          Move-Item -Force dist/SecureEncryptionSystem.exe dist/windows/SecureEncryptionSystem.exe
          Compress-Archive -Path dist/windows/* -DestinationPath dist/windows/SecureEncryptionSystem.zip
          echo "archive=dist/windows/SecureEncryptionSystem.zip" >> $GITHUB_ENV

      - name: Commit Changes to dist
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/windows/*
          git commit -m "Update Windows dist artifacts"
          git push origin HEAD

  build-linux:
    name: Build EXE for Linux
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull The latest Repository
        run: |
          git pull

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean Previous Builds
        run: |
          rm -rf dist/linux/*

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile main.py --name SecureEncryptionSystem

      - name: Package Executable
        run: |
          echo "Packaging Linux executable..."
          mkdir -p dist/linux
          mv dist/SecureEncryptionSystem dist/linux/SecureEncryptionSystem
          zip -j dist/linux/SecureEncryptionSystem.zip dist/linux/SecureEncryptionSystem
          echo "archive=dist/linux/SecureEncryptionSystem.zip" >> $GITHUB_ENV

      - name: Commit Changes to dist
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/linux/*
          git commit -m "Update Linux dist artifacts"
          git push origin HEAD
