name: Python Lint and Format

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Tools
        run: |
          pip install black flake8 isort

      - name: Format Code with Black
        run: black .

      - name: Lint Code with Flake8
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8
          flake8 .

      - name: Auto-fix imports with isort
        run: isort .

      - name: Push changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-fix: Code formatting and imports sorted"
          git push origin main
